server:
  config:
    logLevel: "debug,info"

    numHistoryShards: 512

    persistence:
      default:
        driver: "valkey"

        valkey:
          hosts: 
            - "valkey-cluster-0.valkey-cluster.default.svc.cluster.local:6379"
            - "valkey-cluster-1.valkey-cluster.default.svc.cluster.local:6379"
            - "valkey-cluster-2.valkey-cluster.default.svc.cluster.local:6379"
          password: ""
          existingSecret: ""
          database: 0
          maxRetries: 3
          poolSize: 20
          enableTLS: false
          dialTimeout: "5s"
          readTimeout: "3s"
          writeTimeout: "3s"
          clusterMode: true

      visibility:
        driver: "valkey"

        valkey:
          hosts: 
            - "valkey-cluster-0.valkey-cluster.default.svc.cluster.local:6379"
            - "valkey-cluster-1.valkey-cluster.default.svc.cluster.local:6379"
            - "valkey-cluster-2.valkey-cluster.default.svc.cluster.local:6379"
          password: ""
          existingSecret: ""
          database: 1
          maxRetries: 3
          poolSize: 20
          enableTLS: false
          dialTimeout: "5s"
          readTimeout: "3s"
          writeTimeout: "3s"
          clusterMode: true

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: false

schema:
  createDatabase:
    enabled: false
  setup:
    enabled: false
  update:
    enabled: false
